# Generated by Django 5.0.6 on 2024-06-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='product/images/thumbnail/'),
        ),
    ]
