# Generated by Django 5.0.6 on 2024-05-29 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_rename_userprofile_userprorfile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userprorfile',
            new_name='Userprofile',
        ),
    ]
